name: BUILD
on:
  push:
    branches:
      - "develop"

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install cmake
        run: sudo apt update && sudo apt install -y cmake gcc-arm-none-eabi
      - name: make build dir
        run: mkdir build
      - name: cmake configure
        run: cd build && cmake ../
      - name: cmake build
        run: cd build && cmake --build . -j
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "build/freedeck-pico.uf2"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: "dev-${{ steps.vars.outputs.sha_short }}"
